[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

The following diagram represents the functional requirements of the application.

[plantuml,"Sequence requirements_use_case_digram",png]
----
@startuml

actor Client as client

package ArquiSocks {
  usecase "Add to cart" as addToCart
  usecase "Place order" as placeOrder
  usecase "Login" as login
  usecase "Signin" as signin
  usecase "View orders" as viewOrders
  usecase "View products" as viewProducts
}

cloud Database
cloud SolidPod
cloud MapsAPI

client --> viewProducts
client --> addToCart
client --> placeOrder
client --> login
client --> signin
client --> viewOrders

Database -u-> viewProducts
Database -u-> placeOrder
Database -u-> viewOrders
Database -u-> signin
Database -u-> login
SolidPod -u--> login
SolidPod -u--> signin
MapsAPI -u--> placeOrder

@enduml
----

List of requirements:

* The system will emulate an online shop where the users will be able to select and buy products.
* The system will calculate the shipping costs of the selected products based on the shipping information provided by the 
    user's pod.
* The system will show the user the total price for the products selected.
* The system will register the user's order and will proceed with the shipping.
* The system will show the user a list of all its orders.

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

[options="header",cols="1,2,2"]
|===
|Nº|Quality|Motivation

|1|Confidentiality|The application will respect client's privacy. Users are going to manage their personal information stored in Solid Pods.
|2|Availability|The application will be available the majority of time, specially at client reviews. System availability will always be above 97%, with about 15 hours of maintenance every three weeks.
|3|Usability|The GUI will be easy to use for any user, especially non-technical users. We will do usability tests with different user profiles.
|4|Accesibility| Provide equal access and opportunities to people. Increase the number of customers using the application.
|5|Efficiency|Server's response is going to be under 0.5 seconds. This value is considered the minimum acceptable waiting time by users all over the net. Waiting times upper 0.5 seconds are usually negative for websites' popularity.
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role|Description|Expectations
| _Client_ | _Fictitious company that hires us to develop DeDe application._ | _They expect continuous and responsible work. In addition, a product that reflects what has been learned in the course._
| _Development team + Software Architects_ | _Formed by group ES5A students._ | _Learn about Software Architecture and teamwork._
| _Users_ | _People interested in buying online products while maintaining their privacy._ | _To have an application that allows making purchases and at the same time managing the shared data._
| _Suppliers_ | _These are the distribution centers of the products offered in the application._| _Deliver orders to users._
| _Inrupt_ | _Company founded by Tim Berners-Lee._ | _Make known the SOLID project and promote its development._
|===
