[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
The following diagram represents the functional requirements of the application... (Link here Use Case diagram).

List of requirements:

* The system will emulate an online shop where the users will be able to select and buy products.
* The system will calculate the shipping costs of the selected products based on the shipping information provided by the 
    user's pod.
* The system will show the user the total price for the products selected.
* The system will registered the user's order and will proceed with the shipping.
* The system will show the user a list of all its orders.

****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

Most important quality goals could be the ones that are exposed right here:

[options="header",cols="1,2,2"]
|===
|Nº|Quality|Motivation
|1|Accesibility|Reaching at least AA accesibility level in order to pass EU minimum requirements. This will improve the number of clients using the application. It will be measured using online tools to prove that.
|2|Confidentiality|The application will respect client's privacy. This website will always ask users to use their personal information because it will be stored in a personal pod using SOLID. Clients are going to manage their personal details.
|3|Efficiency|Server's response is going to be under 0.5 seconds. This value is considered the minimum acceptable waiting time by users all over the net. Waiting times upper 0.5 seconds are usually negative for websites' popularity.
|4|Usability|The GUI will be the most user-friendly for noob users. We will make usability tests with users who do not know any about the application.
|5|Availability|The application will be available the majority of time. System's availability will always be upper to 98%. This will reduce money loss due to system failures.
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
