[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Sign in

[plantuml,"Sequence diagram_signIn", png]
----
@startuml
actor User
participant WebApp
database SOLID
User-> SOLID: Login request
User-> SOLID: Enter credentials
alt User exists
    SOLID--> WebApp: Returns the user
    WebApp-> User: User logged in
else User doesn't exists
    SOLID--> WebApp: Denied authentication
end
@enduml
----

=== View orders and products

[plantuml,"Sequence diagram",png]
----
@startuml
actor User
User -> Webapp: Request orders done
participant Restapi
database Database
Webapp -> Restapi: Get orders by user
Webapp <-- Restapi: List of user's orders
Restapi -> Database: Get orders

... **non related temporally** ...

User -> Webapp: Show products
Webapp -> Restapi: Get products
Restapi -> Database: Get products
Webapp <-- Restapi: List of products
@enduml
----
Many details to keep in mind:

* The user will interact with UI elements of the webapp such as buttons. These elements trigger events to the restapi.
* Restapi will manage requests in order to get a response from database system. The response will be shown by the webapp in diferent views.


=== Add product to cart 
[plantuml,"Sequence diagram_AddProduct",png]
----
@startuml
actor User
participant Webapp
participant Restapi

User -> Webapp: Click on a product
Webapp -> Restapi: Add product
User <-- Webapp: Product added correctly
@enduml
----

=== Delete product from cart 
[plantuml,"Sequence diagram_DeleteProduct",png]
----
@startuml
actor User
User -> Webapp: Enter shopping cart
User <-- Webapp: Show cart
User -> Webapp: Click on delete product
participant Restapi
Webapp -> Restapi: Delete product from cart
alt Deletion confirmed
Webapp <-- Restapi: Product deleted
User <-- Webapp: Update cart
else Deletion error
Webapp <-- Restapi: Product not deleted
User <-- Webapp: Don't update cart
end
@enduml
----

=== Confirm purchase
[plantuml,"Sequence diagram_Confirm_purchase",png]
----
@startuml
actor User
participant WebApp
participant Restapi
database SOLID
database Database
User-> WebApp: Enter shopping cart
User<-- WebApp: Return shopping cart
User-> WebApp: Checkout order
alt Checkout confirmed
    User<- WebApp: Ask for personal information
    User-> WebApp: Grant permission
    WebApp-> SOLID: Get information
    WebApp<-- SOLID: Return information
... **Payment process** ...
    Restapi-> Database: Save order
    Restapi--> WebApp: Order saved
    WebApp--> User: Order confirmed
else Checkout error
    WebApp--> User: Error with payment
end
@enduml
----

=== Register the sale event
[plantuml,"Sequence diagram_Register_sale_event",png]
----
@startuml
actor User
participant WebApp
participant Restapi
participant MapsAPI
database SOLID
database Database
User -> WebApp: Request to confirm order
WebApp -> SOLID: Get user's directions
WebApp <-- SOLID: Return directions
User -> WebApp: Select direction
WebApp -> Restapi: Get shipping price
Restapi -> MapsAPI: Calculate distance
Restapi <-- MapsAPI: Returns distance
WebApp <-- Restapi: Returns shipping cost
User <-- WebApp: Show total and shipping price
User -> WebApp: Confirm order
... **Payment process** ...
Restapi -> Database: Save order
WebApp --> User: Show success message
@enduml
----
