[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Sign up and sign in

[plantuml,"Sequence diagram_signUp_signIn", png]
----
actor User
participant WebApp
database Restapi
database SOLID
User-> WebApp: Enter credentials
WebApp -> Restapi: Create user
Restapi -> Restapi: Exists
alt User already exists
    Restapi -> WebApp: Error
else Not registered
    Restapi -> SOLID: Exists
    alt Exists in SOLID
        Restapi -> Restapi: Insert
        Restapi -> WebApp: Created
    else Doesn't exist in SOLID
        Restapi -> WebApp: Error
    end
end
User-> WebApp: Enter credentials
WebApp-> Restapi: Login request
alt User exists
    Restapi-> WebApp: Returns the user
    WebApp-> User: User logged in
else User doesn't exists
    Restapi-> WebApp: Denied authentication
end
----

=== View orders and products

[plantuml,"Sequence diagram",png]
----
actor User
User -> Webapp: Request orders done

database Restapi
Webapp -> Restapi: Get orders by user
Webapp <- Restapi: List of user's orders

... **non related temporally** ...

User -> Webapp: Show products
Webapp -> Restapi: Get products
Webapp <- Restapi: List of products
----
Many details to keep in mind:

* The user will interact with UI elements of the webapp such as buttons. These elements trigger events to the restapi.
* Restapi will manage requests in order to get a response from database system. The response will be shown by the webapp in diferent views.


=== Add product to cart 
[plantuml,"Sequence diagram_AddProduct",png]
----
@startuml
actor User
participant Webapp
database Restapi
database Server
database Database

User -> Webapp: Click on a product
Webapp -> Restapi: Add product to cart
alt User is logged in
    Restapi -> Database: Add product to database
else Else
    Restapi -> Server: Add product to server's session
end

User <-- Webapp: Product added correctly
@enduml
----
Many details to keep in mind:

* Depending on whether the user is logged in or not, the product is stored temporarily in the session or persistently in the database. 

=== Confirm purchase

[plantuml,"Sequence diagram_Confirm_purchase",png]
----
actor User
participant WebApp
database Restapi
database SOLID
User-> WebApp: Enter shopping cart
User<-- WebApp: Return shopping cart
User-> WebApp: Checkout order
alt Checkout confirmed
    User<- WebApp: Ask for personal information
    User-> WebApp: Grant permission
    WebApp-> Restapi: Check necessary information
    Restapi-> SOLID: Get information
    Restapi<-- SOLID: Return information
... **Payment process** ...
    Restapi-> Restapi: Save order
    Restapi--> WebApp: Order saved
    WebApp-> User: Order confirmed
else Checkout error
    WebApp-> User: Error with payment
end
----