[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[plantuml,"Deployment_view_diagram", png]
----
@startuml
node "<<device>> \n Client" as client{
component "<<execution enviroment>> \n Browser"{
rectangle Website
}
}

node "Web server (Heroku)" as webserver{
component "<<execution enviroment>> \n DeDe"{
node WebApp
node RestAPI
}
}

node "<<device>> \n Database Server" as db{
component "<<execution enviroment>> \n MongoDB Atlas"{
database MongoDB
}
}

node "<<device>> \n Solid Pod Server" as solid{
component "<<execution enviroment>> \n Inrupt Pod Spaces"{
database UserPods
}
}

client --> webserver : http
WebApp --> RestAPI : use
RestAPI --> db : use
RestAPI --> solid : use
@enduml
----
Motivation::
The user will access our app through a website which will communicate with the Web server hosted by Heroku. Then, the Webapp will use the RestAPI to respond the user's requests. The RestAPI will use both MongoDB and the Solid pod from the user in order to correctly respond the WebApp request.

Quality and/or performance features::
The performance will depend mostly on the user's internet connection and device hardware, since most of the infraestructure depends on external services (MongoDB, Inrupt, etc.). However, we can increase the performance of the application focusing on writing better and most efficient code.

.Mapping of building blocks to infrastructure
|===
|Element|Description
| Client | Device use by the user to interact with the app.
| Web server | Server where we will have the app running, in our case, Heroku.
| WebApp | Frontend of the app. 
| RestAPI | Backend of the app. 
| Database Server | Server with our Database, in our case, MongoDB Atlas.
| Solid Pod Server | Solid pods used by the users to store their personal information.
|===

