[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
=== MERN Stack usage

Context:: 

We need a set of different technologies and frameworks that can work well together in order to build our project. 

Decision::

As we are restricted to use the link:02_architecture_constraints.adoc[React] framework, we might as well use these technologies (MongoDB, Express and Node.JS) knowing that there is a lot of information about them working together.

Status::

Accepted.

Consequences::

Having this much information about how to combine these technologies will help the team during the development to create a much more robust application.
