[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

[options="header"]
.List of risks
|===
|Risk|Explanation|Measures
|Lack of time||
|Abandonment of a team member||
|Not enough experience on technologies which we need to use. They are Typescript, React, Node.js, Express and SOLID.||
|Lack of communication||
|Unproductive meetings||
|Problems with git||
|English||
|===

[options="header"]
.List of technical debts
|===
|Technical debts|Explanation|Measures
|||
|===

